refactor: update metrics page service call
SigNoz/signoz pull request #1323
Opened 2022-06-28 05:55 UTC by sf-pchakraborty

Update metric page service call using useQuery from react-query.

Close https://github.com/SigNoz/engineering-pod/issues/479

2022-08-09 04:55 UTC, sf-pchakraborty commented
@palashgdev @pranshuchittora 

Can you please review?

2022-12-06 11:42 UTC, pranay01 commented
@sf-pchakraborty Is this PR refactoring from a frontend side? Will end users see an impact of this?

2022-12-09 04:50 UTC, palashgdev requested changes

2022-12-09 04:50 UTC, palashgdev commented on frontend/src/pages/Metrics/index.tsx
> +			queryFn: () =>
can we add the query key also

2022-12-09 04:50 UTC, palashgdev commented on frontend/src/pages/Metrics/index.tsx
> +					status,
also please remove the metrics reducer

2022-12-09 04:50 UTC, palashgdev commented on frontend/src/pages/Metrics/index.tsx
> +	if (isError) {
no need for this check we can show the table with whatever data it has but no need to hide it please show toast in case of error

2022-12-09 04:50 UTC, palashgdev commented on frontend/src/pages/Metrics/index.tsx
> -	if (loading) {
sample here also please utilise table loading for loading

2022-12-09 04:51 UTC, palashgdev commented
> @sf-pchakraborty Is this PR refactoring from a frontend side? Will end users see an impact of this?

No @pranay01 this more kind of a data refactoring

2022-12-20 13:24 UTC, closed without merging

2022-12-21 04:57 UTC, sf-pchakraborty commented
This change was opened more than 6 months ago. There's some issue with the branch currently. I will open a fresh PR with the changes requested upon review by @palashgdev