Create codeql.yml
SigNoz/signoz pull request #1361
Opened 2022-07-06 05:25 UTC by palashgdev

2022-07-13 11:27 UTC, prashant-shahi requested changes

2022-07-13 11:27 UTC, prashant-shahi commented on .github/workflows/codeql.yml
> +        language: [ 'go', 'javascript', 'python' ]
I don't think `python` would be required here.

2022-07-13 11:27 UTC, prashant-shahi commented on .github/workflows/codeql.yml
> +    - cron: '21 11 * * 0'
> 21 11 * * 0

That cron expression translates to "11:21am every Sunday". Any reason for that?

Alternatives would be:
- 10am every sunday: `0 10 * * 0`
- 10am every day: `0 10 * * *`
- 10am every week days: `0 10 * * 1-5`

2022-07-13 11:27 UTC, prashant-shahi commented on .github/workflows/codeql.yml
> +    branches: [ "develop", main ]
quotes are optional.

Also, we should keep it consistent: either use quotes or not.

2022-07-14 18:50 UTC, prashant-shahi approved these changes
Workflow changes look good..

Check with @pranshuchittora for frontend related changes.

2022-07-21 05:59 UTC, pranshuchittora approved these changes

2022-07-21 05:59 UTC, pranshuchittora commented
Pls, resolve the merge conflicts. WIll re-review after that

2022-07-25 05:00 UTC, closed without merging