feat: make SigNoz rpc aware
SigNoz/signoz pull request #1366
Opened 2022-07-07 13:39 UTC by srikanthccv

Also see https://github.com/SigNoz/opentelemetry-collector-contrib/pull/1308 for data model changes.

Fixes #1252

2022-07-08 07:48 UTC, palashgdev requested changes

2022-07-08 09:29 UTC, pranshuchittora requested changes
I and @palashgdev were checking out this PR and found out one unhandled BE case.

![Screenshot 2022-07-08 at 14 58 24](https://user-images.githubusercontent.com/32242596/177962521-e0847fec-6ef9-443b-8f3c-0dfdb4ab3ef2.png)

2022-07-08 15:07 UTC, srikanthccv commented
@pranshuchittora some didn't make it to collector image earlier. Please take another look.

2022-07-13 11:17 UTC, makeavish commented
@srikanthccv 
I think we should update the [logic](https://github.com/SigNoz/signoz/blob/bf3e9eff699c2fcb7e798a081a6e17fef145dd8c/pkg/query-service/app/clickhouseReader/reader.go#L1758) of GetFilteredSpans table too where we are using gRPC and HTTP status code, we can directly use new status code. But as we discussed we can update that in next release as we are not going ahead with migration. Creating an [issue](https://github.com/SigNoz/signoz/issues/1386) for this. 
 
Please resolve merge conflicts. Everything else LGTM.

2022-07-13 11:17 UTC, makeavish submitted a review, later dismissed

2022-07-14 04:53 UTC, makeavish approved these changes

2022-07-14 04:53 UTC, ankitnayan approved these changes

2022-07-14 04:54 UTC, merged