refactor: start_docker()
SigNoz/signoz pull request #1410
Opened 2022-07-16 00:48 UTC by AkshayAwate

Running a command and then checking its exit status $? against 0 is redundant. 
More info can be found: https://www.shellcheck.net/wiki/SC2181
If this is good to go, then we can fix other functions code.
Thanks

2022-07-17 10:54 UTC, prashant-shahi requested changes
Thanks for the pull request!

Can you also address similar ones in line number 268, 272 and 290?

```
[Line 268:](javascript:setPosition(268, 15))
        if (( $EUID != 0 )); then
              ^-- [SC2004](https://www.shellcheck.net/wiki/SC2004) (style): $/${} is unnecessary on arithmetic variables.
 
[Line 272:](javascript:setPosition(272, 19))
            if [[ $? -ne 0 ]] && ! $sudo_cmd -v; then
                  ^-- [SC2181](https://www.shellcheck.net/wiki/SC2181) (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.
 
[Line 290:](javascript:setPosition(290, 7))
if (( $EUID != 0 )); then
      ^-- [SC2004](https://www.shellcheck.net/wiki/SC2004) (style): $/${} is unnecessary on arithmetic variables.
 
[Line 307:](javascript:setPosition(307, 7))
if [[ $? -ne 0 ]]; then
      ^-- [SC2181](https://www.shellcheck.net/wiki/SC2181) (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.
```

2022-07-17 10:54 UTC, prashant-shahi commented on deploy/install.sh
> +            if ! docker ps > /dev/null && true; then
Good practice :+1:

2022-07-17 15:18 UTC, AkshayAwate commented
@prashant-shahi since there is no arithmatic calculation involved using `$EUID`, we can ignore refactoring 
[L268](https://github.com/SigNoz/signoz/blob/develop/deploy/install.sh#L268) and [L290](https://github.com/SigNoz/signoz/blob/develop/deploy/install.sh#L290)

2022-07-20 17:58 UTC, prashant-shahi commented
@AkshayAwate `shellcheck` was asking to use `EUID` instead of `$EUID` for the arithmetic operation.
But anyways, we can address that and other best practices later.

2022-07-20 18:00 UTC, merged