feat: introduce search trace ID component
SigNoz/signoz pull request #1551
Opened 2022-09-07 05:23 UTC by makeavish

2022-09-07 13:13 UTC, srikanthccv commented on frontend/src/container/Trace/Filters/Panel/PanelBody/index.tsx
> +			{type === 'duration' ? <Duration /> : type==='traceID' ? <TraceID />: <CommonCheckBox name={type} />}
Could a type and its corresponding render component be passed in from props themselves and get rid of nested ternary op?

2022-09-08 11:46 UTC, pranshuchittora commented on frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
> +// import { getMs } from './util';
remove if not required

2022-09-08 13:27 UTC, pranshuchittora requested changes
Few changes
- Add loading indication
- Get / Update value in the URL params. Also read from URL
- Clear ALL should work

2022-09-12 10:36 UTC, makeavish commented on frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
> +			if (value !== '') {
Yes in case user removes traceID we have to fetch filters again

2022-09-12 10:37 UTC, makeavish commented on frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
> +		setIsLoading(false);
Done

2022-09-12 10:59 UTC, makeavish commented on frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
> +				onChange={(e) => setUserEnteredValue(e.target.value)}
Done

2022-09-12 11:28 UTC, makeavish commented on frontend/src/container/Trace/Filters/Panel/PanelBody/index.tsx
> +			{type === 'duration' ? (
Done

2022-09-12 14:05 UTC, merged