fix: reuse the query engine and storage for alerts pqlEngine
SigNoz/signoz pull request #1558
Opened 2022-09-09 13:17 UTC by srikanthccv

As described here https://github.com/SigNoz/engineering-pod/issues/728#issuecomment-1240219565 the pqlEngine creates its own client and the same time series data is loaded twice making query service crash in environments that have enough memory resources. This change makes it use the same engine and storage by exposing them from the reader interface.

2022-09-09 15:29 UTC, ankitnayan requested changes

2022-09-10 07:35 UTC, ankitnayan approved these changes

2022-09-11 06:03 UTC, ankitnayan approved these changes

2022-09-12 06:51 UTC, srikanthccv commented
@mindhash will be testing this on the staging instance.

2022-09-12 07:00 UTC, merged