Feat/custom func get sub tree spans
SigNoz/signoz pull request #1648
Opened 2022-10-19 12:57 UTC by makeavish

2022-11-21 11:12 UTC, palashgdev requested changes

2022-11-21 11:12 UTC, palashgdev commented on frontend/src/api/trace/getTraceItem.ts
> +			url: `/traces/${props.id}?spanId=${props.spanId || ''}&levelUp=${props.levelUp || ''}&levelDown=${props.levelDown || ''}`,
please make util for this one ... if value is present then only append in the string else not

2022-11-21 11:12 UTC, palashgdev commented on frontend/src/container/TraceDetail/index.tsx
> +				search: `?spanId=${activeSelectedId}&levelUp=${levelUp}&levelDown=${levelDown}`,
same here

2022-11-21 11:12 UTC, palashgdev commented on frontend/src/container/TraceDetail/index.tsx
> +	const [levelUp] = useState<string | null>(urlQuery.get('levelUp'));
if we are not updating the state probably there is no meaning of `useState`

2022-11-21 11:12 UTC, palashgdev commented on frontend/src/pages/TraceDetail/index.tsx
> +	const [spanId] = useState<string | null>(urlQuery.get('spanId'));
same here

2022-11-21 11:12 UTC, palashgdev commented on frontend/src/types/api/trace/getTraceItem.ts
> +import internal from "stream";
remove this one

2022-11-21 12:34 UTC, makeavish commented on frontend/src/types/api/trace/getTraceItem.ts
> +import internal from "stream";
Done

2022-11-22 07:27 UTC, palashgdev requested changes

2022-11-22 07:27 UTC, palashgdev commented on frontend/src/container/TraceDetail/utils.ts
> +				urlParams = `?${key}=${value}`;
can you please decodeURI and encodeURI value also ?

2022-11-22 07:27 UTC, palashgdev commented on frontend/src/container/TraceDetail/utils.ts
> +				urlParams = `?${key}=`;
handle with try and catch as there is `URI malformed`

for reference: `k8s_pod_name%20NIN%20(%27asd%27)asd3daafc+q32easdc%%%`

2022-11-23 05:39 UTC, palashgdev requested changes

2022-11-23 05:39 UTC, palashgdev commented on frontend/src/api/trace/getTraceItem.ts
> +		const paramsMap = {
there is no need to create new object called paramMap we can destructure

2022-11-23 05:39 UTC, palashgdev commented on frontend/src/container/Trace/TraceTable/index.tsx
> +		return `${ROUTES.TRACE}/${record.traceID}${urlParams}`;
```suggestion
		return `${ROUTES.TRACE}/${record.traceID}${formUrlParams({
			spanId: record.spanID,
			levelUp: 0,
			levelDown: 0,
		})}`;
```

2022-11-23 05:39 UTC, palashgdev commented on frontend/src/container/TraceDetail/index.tsx
> +				search: `${urlParams}`,
```suggestion
				search: `${formUrlParams({
				  spanId: activeSelectedId,
				  levelUp,
				  levelDown,
				})}`,
```

2022-11-23 09:23 UTC, palashgdev submitted a review, later dismissed
LGTM

2022-11-24 08:30 UTC, palashgdev submitted a review, later dismissed

2022-11-24 11:34 UTC, mindhash approved these changes
LGTM. The metric range API should be extended in future releases.

2022-11-24 12:48 UTC, merged