feat: drag select timeframe on charts
SigNoz/signoz pull request #2018
Opened 2023-01-11 10:22 UTC by volodfast

Issue [1985](https://github.com/SigNoz/signoz/issues/1985)

2023-01-12 10:37 UTC, palashgdev requested changes

2023-01-12 10:37 UTC, palashgdev commented on frontend/src/container/MetricsApplication/Tabs/Overview.tsx
> +			const startTimestamp = Math.trunc(start);
@volodfast startTimestamp is in `milliseconds` and if we supply in `nanoseconds` we don't need to change the internals of the global component

2023-01-12 11:35 UTC, palashgdev approved these changes

2023-01-16 08:12 UTC, palashgdev requested changes

2023-01-16 10:07 UTC, palashgdev approved these changes

2023-01-16 10:07 UTC, palashgdev commented
@ankitnayan can you please verify from your end to

2023-01-17 08:19 UTC, palashgdev approved these changes

2023-01-17 11:29 UTC, ankitnayan approved these changes

2023-01-17 11:30 UTC, merged