FIX: Exported dashboard include response of the queries #1981
SigNoz/signoz pull request #2052
Opened 2023-01-15 04:01 UTC by FellipeMTX

Issue solved: #1981 
I created a new ''const'' according to the issue's request and set this const to be the parameter of the download function. I had trouble reproducing the error, but I think this solution should work.
Image of console.log of new const(which will be downloaded):
![Query](https://user-images.githubusercontent.com/102544529/212522312-4a498248-ff03-4a28-9e51-550fe650f0e1.png)

2023-01-16 10:20 UTC, palashgdev requested changes

2023-01-16 10:20 UTC, palashgdev commented on frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
>  						onClick={(): void => {
can make use of closure which will avoid creation of inline function

2023-01-16 10:20 UTC, palashgdev commented on frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
> +	const cleanedQueryData = selectedData = {...selectedData, widgets: selectedData.widgets?.map((widget) => ({
can we move this logic to utils ?

2023-01-25 14:42 UTC, palashgdev requested changes

2023-01-25 14:42 UTC, palashgdev commented on frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
> +							console.log(selectedDataCleaned, 'SDC');
@FellipeMTX console

2023-01-25 14:43 UTC, palashgdev commented
Apart from this one PR looks good to me ,Thanks for raising the PR @FellipeMTX :-D

2023-01-30 08:08 UTC, palashgdev approved these changes

2023-01-30 10:36 UTC, prashant-shahi approved these changes
LGTM :shipit:

2023-01-30 10:37 UTC, merged