feat: add ability to change panel type
SigNoz/signoz pull request #2383
Opened 2023-02-26 02:27 UTC by gitstart

Fixes #709 

## Demo
https://www.loom.com/share/8cf3e1a6d45b4009904cea196e07a52d

2023-02-27 09:26 UTC, palashgdev requested changes

2023-02-27 09:26 UTC, palashgdev commented on frontend/src/container/NewWidget/index.tsx
> +		const url = new URL(window.location.href);
can we use useLocation hook here

2023-02-27 09:26 UTC, palashgdev commented on frontend/src/container/NewWidget/index.tsx
> +		window.history.replaceState({}, '', url);
can we use history from `lib/history`

2023-02-27 09:27 UTC, palashgdev requested changes

2023-02-27 09:27 UTC, palashgdev commented on frontend/src/container/NewWidget/RightContainer/index.tsx
> +				<Option value="VALUE">Value</Option>
can we make use of this config `/frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts`

2023-02-28 05:23 UTC, gitstart commented
Hi @palashgdev, requested changes have been made. Please take a look 🙏

2023-03-07 11:25 UTC, palashgdev approved these changes

2023-03-07 11:25 UTC, merged

2023-03-07 11:35 UTC, srikanthccv commented
Just by looking at the change, I don't see anywhere where the underlying query was modified, which is the real functional part of the change panel type. Is this tested?

2023-03-07 12:05 UTC, palashgdev commented
> Just by looking at the change, I don't see anywhere where the underlying query was modified, which is the real functional part of the change panel type. Is this tested?

modification of the query is not incorporated for more info I am disabling this dropdown
https://github.com/SigNoz/signoz/issues/2410

but from this PR at least we have a way to listen onChange