Feat/connect builder graph
SigNoz/signoz pull request #2611
Opened 2023-04-21 08:39 UTC by yeshev

close #2354

2023-04-21 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=2611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=2611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=2611) it.</sub>

2023-04-25 13:59 UTC, palashgdev requested changes

2023-04-26 19:45 UTC, palashgdev commented on frontend/src/container/QueryBuilder/QueryBuilder.tsx
> +	useEffect(
can you check why there is a need to create a new use effect to do the reset?

https://react.dev/learn/removing-effect-dependencies#read-primitive-values-from-objects

2023-04-28 12:31 UTC, srikanthccv submitted a review, later dismissed
Approving the functionality

2023-05-02 13:05 UTC, palashgdev approved these changes

2023-05-02 14:07 UTC, palashgdev approved these changes

2023-05-02 14:08 UTC, merged