chore: update docs regarding yarn v1
SigNoz/signoz pull request #2721
Opened 2023-05-18 07:46 UTC by GermaVinsmoke

2023-05-19 07:45 UTC, palashgdev requested changes

2023-05-19 07:45 UTC, palashgdev commented on CONTRIBUTING.md
> +  **Note:** Please make sure to have classic version of yarn - `v1.22.19` installed in your system
can we have only one note

2023-05-19 07:48 UTC, GermaVinsmoke commented on CONTRIBUTING.md
> +  **Note:** Please make sure to have classic version of yarn - `v1.22.19` installed in your system
Okay, where should we keep it?

2023-05-23 17:28 UTC, palashgdev commented on CONTRIBUTING.md
> +  **Note:** Please make sure to have classic version of yarn - `v1.22.19` installed in your system
maybe at 188 line

2023-05-23 17:47 UTC, palashgdev submitted a review, later dismissed

2023-05-23 17:59 UTC, GermaVinsmoke commented
We can also think of creating a **Prerequisite** section which can be added above other two sections - with docker, without docker.
Prerequisite section can have details for other things also like, node version needs to be above `v16.15.0`

2023-06-07 14:28 UTC, srikanthccv submitted a review, later dismissed
minor suggestion

2023-06-26 12:58 UTC, palashgdev approved these changes

2024-10-26 13:52 UTC, closed without merging

2024-10-26 13:52 UTC, srikanthccv commented
Not relevant anymore.