Fix: stopped flickering of the service map graph
SigNoz/signoz pull request #2736
Opened 2023-05-19 16:07 UTC by s4nju

This PR resolves issue: #1954 and #1846

The issue was happening because of the data getting refreshed, but now while the data is still getting loaded, it is not flickering anymore 😉 

To know more read this issue. https://github.com/vasturiano/react-force-graph/issues/223

2023-06-08 02:00 UTC, srikanthccv commented
Thanks for the PR.

2023-06-26 12:30 UTC, palashgdev requested changes

2023-06-26 12:30 UTC, palashgdev commented on frontend/src/modules/Servicemap/utils.ts
> +export const getNodePositions = (nodes) => {
can have type please for node

2023-06-26 12:32 UTC, palashgdev commented
also I am not able to replicate the above issue in current develop as we are already the graph when we have the data points from backend

2024-12-19 13:02 UTC, closed without merging