feat: added option to download logs in csv format
SigNoz/signoz pull request #2841
Opened 2023-06-06 14:14 UTC by techchintan

Close: https://github.com/SigNoz/signoz/issues/2840

2023-06-06 19:25 UTC, palashgdev commented on frontend/src/container/LogControls/index.tsx
> +	const flattenObject = useCallback(
name of the variable should also convey we are stringifying the nested objects

2023-06-06 19:27 UTC, palashgdev requested changes

2023-06-06 19:27 UTC, palashgdev commented on frontend/src/container/LogControls/index.tsx
> +		const downloadLink = document.createElement('a');
this process can block the thread add loader and see if can use the already created element or remove the node from DOM after the completion

2023-06-07 02:09 UTC, srikanthccv commented
This seems good to me from the functionality perspective (tested with filters, pagination and page sizes, etc..) but I would let others to give it a test also.

2023-06-07 09:51 UTC, palashgdev approved these changes

2023-06-07 10:01 UTC, merged