feat: add the Trace Explorer page with Query Builder
SigNoz/signoz pull request #2843
Opened 2023-06-06 23:32 UTC by dnazarenkosignoz

2023-06-06 23:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=2843) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=2843) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=2843) it.</sub>

2023-06-12 12:07 UTC, palashgdev requested changes

2023-06-12 12:07 UTC, palashgdev commented on frontend/src/pages/TracesExplorer/index.tsx
> +	const location = useLocation();
from `react-router`

2023-06-12 12:07 UTC, palashgdev commented on frontend/src/pages/TracesExplorer/index.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
can we remove this one and updated the dependency

2023-06-12 12:07 UTC, palashgdev commented on frontend/src/types/api/trace/getQueryRange.ts
> +	dataSource: DataSource;
this is already created no need for this one

2023-06-19 10:24 UTC, palashgdev approved these changes, later dismissed

2023-06-19 10:52 UTC, palashgdev submitted a review, later dismissed

2023-06-19 11:31 UTC, palashgdev approved these changes

2023-06-19 12:29 UTC, makeavish commented
Found few issues @dnazarenkosignoz 
1. I see duplicate attribute keys and attribute values API calls when using the filter. (Not related to this PR)
2. Unnecessary aggregate key API calls are being made when clicking on the aggregate attribute field. (Not related to this PR)
3. Stuck on key suggestions API after pressing backspace: https://share.vidyard.com/watch/Sxw3HYQEH6kvXZAKHy1gVR? (Not related to this PR)
4. Unnecessary attribute key call when updating aggregate operator (Not related to this PR)

These issues can be addressed separately: https://github.com/SigNoz/signoz/issues/2932 & https://github.com/SigNoz/signoz/issues/2934

2023-06-19 12:29 UTC, makeavish approved these changes

2023-06-19 12:57 UTC, merged