Footer year updated to be dynamic
SigNoz/signoz pull request #288
Opened 2021-09-02 09:56 UTC by nvamsikrishna05

- Updated the Year in Footer to be dynamic

2021-09-02 14:40 UTC, palash-signoz commented
Hi @nvamsikrishna05 
PR looks good to me. but can we make a variable before return rather than having a logic inside the component?

```js
const fullYear = new Date().getFullYear();

return(
<>
...
{fullYear}
....
</>
)
```

2021-09-02 14:41 UTC, palash-signoz requested changes
Hi @nvamsikrishna05
PR looks good to me. but can we make a variable before return rather than having a logic inside the component?

```js
const fullYear = new Date().getFullYear();

return(
<>
...
{fullYear}
....
</>
)
```

2021-09-03 03:33 UTC, nvamsikrishna05 commented
@palash-signoz implemented the suggested changes. Please review

2021-09-03 04:59 UTC, palash-signoz approved these changes

2021-09-03 05:36 UTC, closed without merging