fix: create and store label when colon is pressed
SigNoz/signoz pull request #2886
Opened 2023-06-10 18:38 UTC by Damans227

Fixes #2692

Currently, the key value pair field in Alert allows a user to put a colon in either key or value. It can cause confusion and make users believe the entire label needs to include both key and value. I would recommend that in addition to using `ENTER` as a way to end a key or value string, we also allow `COLON (:)` to do the same. In this way, the user will have a better experience. [This screen recording](https://www.loom.com/share/4eaa4272413d44f1813ad1c98e3be44e) shows how it works.

2023-06-10 18:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=2886) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=2886) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=2886) it.</sub>

2023-06-11 08:26 UTC, palashgdev requested changes

2023-06-11 08:26 UTC, palashgdev commented on frontend/src/container/FormAlertRules/labels/index.tsx
> +		const processedCurrentVal = replace(e.target?.value, ':', '');
can we use native replace

2023-06-11 08:45 UTC, palashgdev commented
Hi @Damans227 
Thanks for raising the PR can you please the small suggestion though we in process to remove [lodash](https://github.com/SigNoz/signoz/issues/2032)

2023-06-11 15:22 UTC, Damans227 commented on frontend/src/container/FormAlertRules/labels/index.tsx
> +		const processedCurrentVal = replace(e.target?.value, ':', '');
Sure. That sounds good.

2023-06-12 08:58 UTC, palashgdev approved these changes

2023-06-12 09:06 UTC, merged