feat: sort logs in ascending order
SigNoz/signoz pull request #2895
Opened 2023-06-13 10:09 UTC by gitstart

Fixes #2787 

Demo:
https://www.loom.com/share/795c2553f8e14e5fb4b6e590445f5bc8

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-06-14 07:42 UTC, nityanandagohain commented
Also please disable the `go to latest` button when ascending order is selected

2023-06-14 07:58 UTC, palashgdev commented
> The sorting preferences should also be stored locally, it resets on refresh

for this one please update the url and initialise the state from the url if present other fallback to desc

2023-06-14 11:30 UTC, gitstart commented
> In asc mode
> 
> * Next button -> instead of idLt , idGt should be used
> * Prev button -> instead of itGt, idLt should be used
> 

Hi @nityanandagohain, can you please elaborate on this?

2023-06-16 04:35 UTC, nityanandagohain commented
@gitstart , in ASC mode the API params will change i.e

When you click on the next button the API request should send `idGt` in the payload and not `idLt`
And when prev button is clicked , API request should send `idLt` in the payload and not `idGt`

2023-06-20 07:31 UTC, gitstart commented
Hi @nityanandagohain! PR has been updated with the requested changes, please re-review 🙏

2023-06-20 12:28 UTC, nityanandagohain reviewed
The change looks good to me

but, lets say in asc mode I am in nth page by clicking the `prev/next` button n number of times. Now If I try to click on the refresh button near the time button, it still renders the same page and there is not really an option for me to reset unless I manully refresh the browser page. But it should be fine for this use case.

Let me know what you guys think @palashgdev @ankitnayan

2023-06-21 05:54 UTC, nityanandagohain submitted a review, later dismissed

2023-06-21 06:58 UTC, nityanandagohain commented
Fixes https://github.com/SigNoz/signoz/issues/2176

2023-06-26 11:17 UTC, palashgdev requested changes

2023-06-26 11:17 UTC, palashgdev commented on frontend/src/container/LogDetailedView/ActionItem.tsx
> +			const idConditions: Record<string, string> = {};
we have the same logic please avoid duplicates

2023-06-26 11:17 UTC, palashgdev commented on frontend/src/container/LogDetailedView/ActionItem.tsx
> +			const idConditions: Record<string, string> = {};
reference: frontend/src/container/LogsSearchFilter/index.tsx

2023-06-26 11:17 UTC, palashgdev commented on frontend/src/container/LogsSearchFilter/useSearchParser.ts
> +				search: `?q=${updatedQueryString}&order=${order}`,
can we power the order and query from here

```
https://github.com/SigNoz/signoz/blob/1ded475b371f4d0a01874e3c195980f242a6ba4d/frontend/src/constants/query.ts
```

2023-06-26 11:17 UTC, palashgdev commented on frontend/src/pages/Logs/index.tsx
> +		const params = new URLSearchParams(window.location.search);
don't use window use utils from react-router

2023-06-26 11:17 UTC, palashgdev commented on frontend/src/pages/Logs/index.tsx
> +									<Select.Option key="desc">Descending</Select.Option>
can we have enum please just to avoid magic strings

2023-06-29 06:26 UTC, gitstart commented
Hi @palashgdev, we have made the requested change. Please review

2023-06-29 08:27 UTC, palashgdev approved these changes

2023-06-29 08:28 UTC, palashgdev approved these changes

2023-06-29 08:41 UTC, merged