Add cypress github action
SigNoz/signoz pull request #291
Opened 2021-09-03 09:18 UTC by aggmoulik

Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

2021-09-04 07:21 UTC, palash-signoz commented
Hi @aggmoulik 
Thanks for contributing will your PR

2021-09-04 07:35 UTC, aggmoulik commented
I have tried the env just like in the actions documentation but it is not working for some reason.

2021-09-04 08:52 UTC, aggmoulik commented
Hey @palash-signoz, You can refer [here](https://github.com/aggmoulik/signoz/pull/1) to see why tests are not working.
If I am missing something let me know.

2021-10-07 05:34 UTC, pal-sig commented
Hi @aggmoulik 
I am getting time out error

2021-12-05 10:25 UTC, pal-sig requested changes

2021-12-05 10:25 UTC, pal-sig commented on .github/workflows/cypress.yaml
> +          start: yarn dev
@aggmoulik i think dev server start with 3000 port

2021-12-05 10:25 UTC, pal-sig commented on .github/workflows/cypress.yaml
> +          CYPRESS_baseUrl: http://localhost:8080/
can you use env file for same ?

2022-04-05 09:00 UTC, palash-signoz commented
@aggmoulik any update regarding the changes ?

2022-05-12 17:40 UTC, pranay01 commented
Stale PR. Closing

2022-05-12 17:40 UTC, closed without merging