fix: no query_range api call on layout change
SigNoz/signoz pull request #2958
Opened 2023-06-22 03:57 UTC by Rajat-Dabade

Close https://github.com/SigNoz/signoz/issues/2797

2023-06-22 04:51 UTC, palashgdev requested changes

2023-06-22 04:51 UTC, palashgdev commented on frontend/src/container/GridGraphLayout/index.tsx
> +			for (let i = 0; i < layout.length; i += 1) {
```suggestion
const setLayoutFunction = useCallback(
	(layout: Layout[]) => {
		layout.forEach((item, i) => {
			const currentWidget =
				widgets?.find((widget) => widget.id === item.i) || ({} as Widgets);
			layouts[i] = {
				...item,
				Component: (): JSX.Element => (
					<Graph
						name={currentWidget.id}
						widget={currentWidget}
						yAxisUnit={currentWidget?.yAxisUnit}
						layout={layout}
						setLayout={setLayout}
						onDragSelect={onDragSelect}
					/>
				),
			};
		});

		setLayout((layouts) => layouts);
	},
	[widgets, onDragSelect, layouts],
);
```

2023-06-22 06:53 UTC, makeavish commented
@Rajat-Dabade Is it required to call query range API, when we save the layout?
IMO it's not required as layout change is not related to query range API.
cc: @palashgdev

2023-06-22 07:10 UTC, Rajat-Dabade commented
@makeavish, It should not be required, should we do it as a part of this PR, or should create a new issue for that?
Thoughts @palashgdev

2023-06-22 07:17 UTC, makeavish commented
> @makeavish, It should not be required, should we do it as a part of this PR, or should create a new issue for that? Thoughts @palashgdev

This is happening after these PR changes and is related to current changes only. On staging we don't make query range API on saving layout. So I think it should be part of this PR.

2023-06-22 07:19 UTC, Rajat-Dabade commented
@makeavish, Okay I got it. Looking into it.

2023-11-29 05:30 UTC, makeavish commented
I think this PR is obsolete and can be closed, reopen if needed.

2023-11-29 05:30 UTC, closed without merging