feat: add the table view for the traces explorer
SigNoz/signoz pull request #2964
Opened 2023-06-22 14:21 UTC by dnazarenkoo

Close: [2336](https://github.com/SigNoz/signoz/issues/2336)

2023-06-22 14:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=2964) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=2964) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yeshev<br/>:x: Nazarenko19<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=2964) it.</sub>

2023-06-27 13:57 UTC, makeavish commented
In case of table view it has been decided that we will fix aggregate interval to global time interval.
@dnazarenkoo Please update this

2023-06-27 13:58 UTC, makeavish commented
Legend format breaks in table view
<img width="1243" alt="Screenshot 2023-06-27 at 19 28 13" src="https://github.com/SigNoz/signoz/assets/9512100/93e778dc-4605-4fe7-aed8-c67dfee1f14d">

2023-06-27 14:19 UTC, makeavish commented
Aggregate operator along with aggregate attribute should be show in table column name.
Example: In below screenshot, `Avg` column name should be replaced by `Avg - durationNano`
<img width="1236" alt="Screenshot 2023-06-27 at 19 43 44" src="https://github.com/SigNoz/signoz/assets/9512100/1b22f14f-b256-4e7c-b2ed-9999ad09ce41">

2023-06-27 14:29 UTC, makeavish commented
Formula broken in table view:
<img width="1276" alt="Screenshot 2023-06-27 at 19 58 45" src="https://github.com/SigNoz/signoz/assets/9512100/f6767ddc-8f5a-4182-95f2-63138dccc161">

2023-06-27 14:50 UTC, makeavish requested changes
Please fix the reported issues

2023-07-18 06:47 UTC, makeavish submitted a review, later dismissed

2023-07-18 06:49 UTC, palashgdev requested changes

2023-07-18 06:49 UTC, palashgdev commented on frontend/src/container/TracesExplorer/TableView/styles.ts
> +	gap: 15px;
use space from antd

2023-07-18 10:08 UTC, palashgdev approved these changes

2023-07-18 10:17 UTC, merged