feat: export panel in logs explorer is added
SigNoz/signoz pull request #2993
Opened 2023-06-28 14:57 UTC by palashgdev

Close https://github.com/SigNoz/signoz/issues/2346

2023-07-03 11:03 UTC, makeavish requested changes
Two issues:

1. Panel is not exported. Just a new dashboard is created
2. Error not shown when exporting is failed due to feature limit exceeded

2023-07-03 13:42 UTC, palashgdev commented
> Two issues:
> 
> 
> 
> 1. Panel is not exported. Just a new dashboard is created
> 
> 2. Error not shown when exporting is failed due to feature limit exceeded

1. panel will be removed if not clicked on save button as this is removed when user moved to widget list page

2. this is client side navigation individual page are already handling this issue

2023-07-07 12:36 UTC, makeavish commented
Gap between action and run query on logs explorer is higher.
Please reduce it. Check trace explorer for reference
<img width="187" alt="Screenshot 2023-07-07 at 18 03 22" src="https://github.com/SigNoz/signoz/assets/9512100/7fa7d258-9c1f-4ba6-b2d7-901c3ebee1bc">

2023-07-07 13:04 UTC, makeavish commented
@yeshev Another issue:
https://www.loom.com/share/0432aa899b7641d4be850506cf5a0065?sid=2822f438-ad05-4fcb-9f26-a531a857b79c
This is common for alerts and panel export.
I think solution would be to switch from `Noop` to `count` when exporting from list/trace view

2023-07-07 13:15 UTC, makeavish commented
Another issue:
Aggregate operator is not exported in alert export
https://www.loom.com/share/0004e1965e1b4de1a1f196a48b9a46eb?sid=0ae8f426-a67c-4325-aff9-746fe754d0f1

2023-07-07 14:44 UTC, yeshev commented
> @yeshev Another issue: https://www.loom.com/share/0432aa899b7641d4be850506cf5a0065?sid=2822f438-ad05-4fcb-9f26-a531a857b79c This is common for alerts and panel export. I think solution would be to switch from `Noop` to `count` when exporting from list/trace view

@makeavish fixed

2023-07-07 14:59 UTC, yeshev commented
> Another issue: Aggregate operator is not exported in alert export https://www.loom.com/share/0004e1965e1b4de1a1f196a48b9a46eb?sid=0ae8f426-a67c-4325-aff9-746fe754d0f1

Fixed

2023-07-07 15:03 UTC, makeavish commented
> > @yeshev Another issue: https://www.loom.com/share/0432aa899b7641d4be850506cf5a0065?sid=2822f438-ad05-4fcb-9f26-a531a857b79c This is common for alerts and panel export. I think solution would be to switch from `Noop` to `count` when exporting from list/trace view
> 
> @makeavish fixed

@yeshev This is only fixed when exporting list/trace view in traces but I can still see this issue when exporting from list view of logs. Please fix the list view of logs.

Also apply same logic when exporting to alerts as well.

2023-07-07 15:28 UTC, makeavish approved these changes

2023-07-07 15:29 UTC, merged