feat: layout is updated for logs-settings
SigNoz/signoz pull request #3220
Opened 2023-07-28 06:23 UTC by palashgdev

2023-07-31 10:28 UTC, Rajat-Dabade requested changes
One minor change, also please share the loom video if possible. Rest LGTM 🚀 .

2023-07-31 10:28 UTC, Rajat-Dabade commented on frontend/src/pages/Settings/config.ts
> +export const commonRoutes = (t: TFunction): RouteTabProps['routes'] => [
Same here `routes` as constant

2023-07-31 13:44 UTC, palashgdev commented
> One minor change, also please share the loom video if possible. Rest LGTM 🚀 .

already using like a constant 😅

2023-08-03 06:27 UTC, nityanandagohain approved these changes

2023-08-03 07:22 UTC, Rajat-Dabade approved these changes

2023-08-03 07:22 UTC, merged