feat: feature flag rpm is being taken care of
SigNoz/signoz pull request #3285
Opened 2023-08-07 19:28 UTC by palashgdev

2023-08-08 03:40 UTC, Rajat-Dabade requested changes
Just a small minor refactoring change, everything else LGTM 👍

2023-08-08 03:40 UTC, Rajat-Dabade commented on frontend/src/container/ServiceApplication/Columns/ServiceColumn.ts
> +interface ITableColumnProps {
Can we move this to `src/container/ServiceApplication/types.ts`

2023-08-08 03:41 UTC, Rajat-Dabade commented
Also, the build pipeline is broken.

2023-08-08 07:48 UTC, Rajat-Dabade approved these changes

2023-08-10 01:18 UTC, makeavish commented
In graph use ops/min instead of op/s when PreferRPM feature flag is true
<img width="347" alt="Screenshot 2023-08-10 at 06 47 45" src="https://github.com/SigNoz/signoz/assets/9512100/429591f8-dcf4-48e2-88bd-8e133a13184f">

2024-05-29 09:06 UTC, closed without merging