feat: add live logs list
SigNoz/signoz pull request #3341
Opened 2023-08-15 14:59 UTC by yeshev

part of #3133

2023-08-21 16:58 UTC, nityanandagohain reviewed
* When no log lines are fetched, it should show something like  "fetching log lines" instead of "no log lines found" cc @palashgdev

2023-08-22 07:25 UTC, yeshev commented
> 

@nityanandagohain Fixed

2023-08-22 12:14 UTC, nityanandagohain requested changes
@yeshev 
* When I resume the id sent is not correct it seems, it should send the id of the last log line received, i.e log line at the top. but it is sending something else.
* The same issue is with search, the id send in the API request is not correct.

2023-08-23 12:13 UTC, nityanandagohain approved these changes

2023-08-25 06:00 UTC, YounixM commented on frontend/src/container/LiveLogs/ListViewPanel/index.tsx
> +	const isFormatButtonVisible = useMemo(
useMemo isn't required here.

2023-08-25 06:06 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
> +	console.log({ logs });
Remove console log

2023-08-25 06:06 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
> +						<Spinner style={{ height: 'auto' }} tip="Getting logs" />
tip can be updated to `Fetching Logs`

2023-08-25 06:07 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +	const selectedFields = useMemo(
useMemo isn't required here.

https://blog.logrocket.com/when-not-to-use-usememo-react-hook/#:~:text=It's%20important%20to%20note%20that,itself%20has%20a%20small%20overhead.

2023-08-25 06:10 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +	const getItemContent = useCallback(
Can you please profile the performance with and without using useCallback and we can then take a call which one to go with.

2023-08-25 06:14 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +	const renderContent = useMemo(() => {
We can move this as another component and use React.memo to have good performance.

2023-08-25 06:14 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +	const isLoadingList = useMemo(() => isConnectionLoading && logs.length === 0, [
useMemo isn't required here.

https://blog.logrocket.com/when-not-to-use-usememo-react-hook/#:~:text=It's%20important%20to%20note%20that,itself%20has%20a%20small%20overhead.

2023-08-25 06:16 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +			{options.format !== 'table' && (
We can use constants for optionsFormat from `frontend/src/constants/optionsFormatTypes.ts`

2023-08-25 06:16 UTC, YounixM commented on frontend/src/container/LiveLogs/LiveLogsList/index.tsx
> +			{logs.length === 0 && <Typography>Fetching log lines</Typography>}
Move `Fetching log lines` to locale file.

2023-08-29 11:34 UTC, palashgdev approved these changes

2023-08-29 11:53 UTC, merged