fix(FE/logs): enable horizontal scroll in logs context
SigNoz/signoz pull request #3407
Opened 2023-08-22 18:33 UTC by CKanishka

Fixes #3400 

**Description**

The content of a log in the Logs Context section was not fully visible and was getting truncated, so adding a horizontal scroll in order for the content to be visible on scrolling. 

**Changes Overview**

https://github.com/SigNoz/signoz/assets/30779692/311db868-45e2-4a30-bc59-fe333a318d3d

2023-08-22 18:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=3407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=3407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=3407) it.</sub>

2023-08-23 02:44 UTC, Rajat-Dabade requested changes
Some minor changes, mostly refactoring ones.

2023-08-23 02:44 UTC, Rajat-Dabade commented on frontend/src/components/Logs/RawLogView/styles.ts
> +	${(props): string =>
Destruction props at parameter level. 
```suggestion
	${({ isTextOverflowEllipsisDisabled,  linesPerRow }): string =>
```

2023-08-23 02:44 UTC, Rajat-Dabade commented on frontend/src/components/Logs/RawLogView/index.tsx
> +	const {
As we are refactoring the code, can you please destructure the props at the parameter level? 
```suggestion
	function RawLogView({
		isActiveLog = false,
		isReadOnly = false,
		data,
		linesPerRow,
		isTextOverflowEllipsisDisabled = false
	}: RawLogViewProps): JSX.Element {
```

2023-08-23 02:44 UTC, Rajat-Dabade commented on frontend/src/components/Logs/RawLogView/index.tsx
> +		isTextOverflowEllipsisDisabled = false,
No need to provide `isTextOverflowEllipsisDisabled` as `false`, as it is already mentioned as `false` in `RawLogView.defaultProps`.  Also please remove the false from `isActiveLog` and `isReadOnly` props.

2023-08-23 02:44 UTC, Rajat-Dabade commented on frontend/src/components/Logs/RawLogView/index.tsx
> +	isTextOverflowEllipsisDisabled?: boolean;
As a part of refactoring, can we move this interface to `components/Logs/RawLogView/types.ts`

2023-08-23 06:31 UTC, CKanishka commented
> Some minor changes, mostly refactoring ones.

@Rajat-Dabade  Addressed the comments

2023-08-23 11:31 UTC, palashgdev approved these changes
LGTM

2023-08-23 16:00 UTC, Rajat-Dabade approved these changes
LGTM

2023-08-24 17:40 UTC, YounixIO approved these changes

2023-08-25 02:19 UTC, merged

2023-08-25 02:27 UTC, srikanthccv commented
@Rajat-Dabade, please squash when you merge to develop. Otherwise, each WIP commit shows up as in release notes and commit history.