fix(FE/dashboard): Configure dashboard drawer UX fixes
SigNoz/signoz pull request #3419
Opened 2023-08-23 14:02 UTC by CKanishka

Fixes #3413 

**Description**

- Added padding to the close button on the header
- Drawer to be auto-closed on save
- Tags alignment and close on blur fixed

**Changes Overview**

https://github.com/SigNoz/signoz/assets/30779692/0050e445-9523-4df9-ab55-de7278e5f9e7

2023-08-24 02:50 UTC, Rajat-Dabade requested changes
One small change, everything else LGTM 🚀

2023-08-24 02:50 UTC, Rajat-Dabade commented on frontend/src/store/reducers/dashboard.ts
> +	generalConfigSaving: false,
```suggestion
	isGeneralConfigSaving: false,
```

2023-08-24 02:50 UTC, Rajat-Dabade commented on frontend/src/types/reducer/dashboards.ts
> +	generalConfigSaving: boolean;
Same here

2023-08-24 06:48 UTC, CKanishka commented
> One small change, everything else LGTM 🚀

Addressed comment

2023-08-24 11:54 UTC, Rajat-Dabade approved these changes
LGTM

2024-07-24 18:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=3419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=3419) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: CKanishka<br/>:white_check_mark: srikanthccv<br/>:x: Rajat Dabade<br/><hr/>**Rajat Dabade** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=3419) it.</sub>

2024-12-19 13:02 UTC, closed without merging