fix: update version check login and other minor UI fixes
SigNoz/signoz pull request #3759
Opened 2023-10-17 13:32 UTC by YounixM

2023-10-17 13:36 UTC, palashgdev approved these changes

2023-10-18 07:20 UTC, Rajat-Dabade requested changes
Some optimisation changes, but everything else looks good to me.

2023-10-18 07:20 UTC, Rajat-Dabade commented on frontend/src/container/BillingContainer/BillingContainer.tsx
> +			onSuccess: processUsageData,
`useEffect` on line 212 can be remove as it is handle here.

2023-10-18 07:20 UTC, Rajat-Dabade commented on frontend/src/utils/app.ts
> +export const checkVersionState = (
```suggestion
export const checkVersionState = (
export const checkVersionState = (currentVersion: string, latestVersion: string): boolean => {
  const versionCore = currentVersion?.split('-')[0];
  return versionCore === latestVersion;
};

```

We can remove the unnecessary if statement as `split` function will return an array containing the original string as its single element if it doesn't find the specified separator in the string

2023-10-18 11:24 UTC, Rajat-Dabade approved these changes
LGTM 🚀

2023-10-18 16:13 UTC, merged