Logs Strip color according to `severity_text`
SigNoz/signoz pull request #4643
Opened 2024-03-04 10:25 UTC by Rajat-Dabade

loom: https://www.loom.com/share/20396b818086401ea9ccc1c94fcfca9f?sid=783bc802-e70d-477e-a1a9-9a54220aeda0

PRD: https://www.notion.so/signoz/PRD-log-strip-color-according-to-severity-text-7eb75bc9d3e3494393005e1276fa38f3?pvs=4

2024-03-04 10:55 UTC, Vikrant2520 submitted a review, later dismissed

2024-03-04 11:06 UTC, Vikrant2520 commented on frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.test.tsx
> +			containerError.querySelector('.line')?.classList.contains('ERROR'),
🔥

2024-03-04 11:06 UTC, Vikrant2520 submitted a review, later dismissed

2024-03-05 11:58 UTC, nityanandagohain requested changes
Doesn't seem to be working here are some example json

```
{
  "body": "testing message debug",
  "id": "2dGdHi6XseXCePhNnOzfWnmrBA6",
  "timestamp": "2024-03-05T17:23:23.808432128+05:30",
  "attributes": {
    "tx1.a": 15361,
    "testattr": "name15361",
    "tx1.b": "15361"
  },
  "resources": {
    "service.instance.id": "instance-13",
    "service.name": "s",
    "telemetry.sdk.language": "python",
    "telemetry.sdk.name": "opentelemetry",
    "telemetry.sdk.version": "1.16.0"
  },
  "severity_text": "ERROR",
  "severity_number": 17,
  "span_id": "",
  "trace_flags": 0,
  "trace_id": ""
}
```
Another one

```
{
  "body": "testing message",
  "id": "2dGdHi6XseXCePhNnOzfWnmrBAo",
  "timestamp": "2024-03-05T17:25:50.420780032+05:30",
  "attributes": {
    "tx1.a": 10753,
    "testattr": "name10753",
    "tx1.b": "10753"
  },
  "resources": {
    "service.instance.id": "instance-13",
    "service.name": "s",
    "telemetry.sdk.language": "python",
    "telemetry.sdk.name": "opentelemetry",
    "telemetry.sdk.version": "1.16.0"
  },
  "severity_text": "WARNING",
  "severity_number": 13,
  "span_id": "",
  "trace_flags": 0,
  "trace_id": ""
}
```

<img width="1003" alt="image" src="https://github.com/SigNoz/signoz/assets/26831659/660a9ca7-413b-4860-9017-1ffd8adfe385">

<img width="1003" alt="image" src="https://github.com/SigNoz/signoz/assets/26831659/621f62df-24eb-43ec-93a9-1ab0d0d7ddee">

2024-03-05 12:38 UTC, nityanandagohain approved these changes

2024-03-06 10:10 UTC, Vikrant2520 approved these changes

2024-03-07 06:33 UTC, YounixM approved these changes

2024-03-07 06:55 UTC, merged