feat: [SIG-571]: added support for has and nhas operator for json filter
SigNoz/signoz pull request #4736
Opened 2024-03-21 13:52 UTC by Vikrant2520

### Summary

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2024-03-21 17:03 UTC, Rajat-Dabade submitted a review, later dismissed

2024-03-22 07:43 UTC, nityanandagohain requested changes
* for check add prefix `body.` as well along with `[*]` .
* Once the check is passed, don't suggest other operators other than has and nhas.

This is because has and nhas works with only json full text search as of now.

2024-03-22 08:02 UTC, nityanandagohain approved these changes

2024-03-22 08:04 UTC, YounixM approved these changes

2024-03-22 08:09 UTC, merged