QB - Logs - Enable TimeShift function
SigNoz/signoz pull request #4792
Opened 2024-04-02 08:19 UTC by YounixM

<img width="1917" alt="Screenshot 2024-04-02 at 1 45 17 PM" src="https://github.com/SigNoz/signoz/assets/3520897/1996b406-1c6c-4d31-9c0d-13c9a32e00de">

<img width="1920" alt="Screenshot 2024-04-02 at 1 47 19 PM" src="https://github.com/SigNoz/signoz/assets/3520897/bfcf964e-ab7f-4769-8df2-9514c6640f84">

2024-04-02 10:18 UTC, nityanandagohain requested changes
* it is using the `/api/v4/query_range`, it should use `/api/v3/query_range` for logs queries.
* in the old dashboards functions options is not showing up

2024-04-03 12:56 UTC, nityanandagohain approved these changes
LGTM

2024-04-03 17:14 UTC, Rajat-Dabade approved these changes
LGTM 🚀

2024-04-03 19:13 UTC, Vikrant2520 approved these changes

2024-04-04 05:35 UTC, merged