feat(FE): add production build & serve local script
SigNoz/signoz pull request #502
Opened 2021-12-13 03:41 UTC by Siddhant-K-code

Signed-off-by: Siddhant Khare <Siddhantkhare2694@gmail.com>

fixes #498

2021-12-13 13:16 UTC, pal-sig requested changes

2021-12-13 13:16 UTC, pal-sig commented on frontend/package.json
> +		"prod": "yarn build && npx serve ./build",
can we remove npx here

2021-12-13 13:16 UTC, pal-sig commented on frontend/package.json
> +		"serve": "^13.0.2",
can we use this as devDependencies here

2021-12-13 13:18 UTC, pal-sig commented
also can you re-route all request to `/index.html` seems it is reflecting 404 when we refresh

2021-12-21 11:06 UTC, pal-sig commented
@Siddhant-K-code still the same issue

2022-02-16 19:02 UTC, Siddhant-K-code commented
are we facing the same issue on `dev` version?
if this is the issue with `build` folder path issues, then we have to make some changes. But I don't think it is because of it.

I think we have to handle some routes for `/`

2022-03-26 12:26 UTC, palash-signoz commented
> are we facing the same issue on `dev` version? if this is the issue with `build` folder path issues, then we have to make some changes. But I don't think it is because of it.
> 
> I think we have to handle some routes for `/`

Yes @Siddhant-K-code

2022-03-26 12:28 UTC, palash-signoz commented
You can use `https://github.com/vercel/serve-handler#rewrites-array`

2022-06-13 11:47 UTC, palashgdev commented
Closing due to inactivity

2022-06-13 11:47 UTC, closed without merging