fix(BUG): Allow users to enter application if no sample data is provided (#478)
SigNoz/signoz pull request #538
Opened 2021-12-19 15:20 UTC by aryanshridhar

This pr essentially resolves the unresponsive behavior of `Continue without instrumentation` button in onboarding modal when the user provides no sample app data to monitor upon.

<strong>Logic</strong>

When no sample data is provided, the metric action is set to `GET_INITIAL_APPLICATION_ERROR` which assigns the error variable as `true`. Due to this, the check statement [here](https://github.com/SigNoz/signoz/blob/6f8b78bd97edccac2b81040e7671936e8b388846/frontend/src/container/MetricsTable/index.tsx#L36) gets `true` and even though the user presses the button, the `SkipOnBoardingModal` component is rendered.
Hence, this pr removes the check statement so that even though error variable is `true`, the user can explore the application.

<strong>Screenshot</strong>

https://user-images.githubusercontent.com/53977614/146680144-a5b022f7-98dd-48c7-964f-2c76ee1b216f.mov

(Once the user presses the button, the `skip_onboarding` is set to `true` and the modal closes)

Fixes #478

2021-12-20 02:28 UTC, pal-sig requested changes

2021-12-20 02:28 UTC, pal-sig commented on frontend/src/container/MetricsTable/index.tsx
> +	if (services.length === 0 && loading === false && !skipOnboarding) {
@aryanshridhar can you please include 

``` services.length === 0 && loading === false && !skipOnboarding && error === true ```

2021-12-20 13:26 UTC, aryanshridhar commented on frontend/src/container/MetricsTable/index.tsx
> +	if (services.length === 0 && loading === false && !skipOnboarding) {
Cool Updated!

2021-12-21 07:11 UTC, pal-sig approved these changes

2021-12-24 06:23 UTC, merged