feat: removed top nav from new alerts landing page
SigNoz/signoz pull request #5538
Opened 2024-07-22 13:44 UTC by rahulkeswani101

### Summary

#### Related Issues / PR's
[#1537]  (https://github.com/SigNoz/engineering-pod/issues/1537)

Before code changes 

![image](https://github.com/user-attachments/assets/c3eec509-a6be-4ac3-b468-5b3f13f69b74)

After code changes

![image](https://github.com/user-attachments/assets/a2e617ab-c840-4ab2-809f-7bea390db386)

2024-07-22 13:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SigNoz/signoz?pullRequest=5538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SigNoz/signoz?pullRequest=5538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SigNoz/signoz?pullRequest=5538) it.</sub>

2024-07-23 06:44 UTC, vikrantgupta25 requested changes
none of this is needed, we have `routeToSkip` in the `src/container/TopNav/index.tsx` and the config is present in the DateTimeSelection file. add the alerts route to that and it should be hidden post that.

2024-07-26 05:38 UTC, vikrantgupta25 approved these changes

2024-07-29 06:12 UTC, YounixM approved these changes

2024-07-29 06:12 UTC, merged