feat: consume the new search bar
SigNoz/signoz pull request #5728
Opened 2024-08-20 20:57 UTC by vikrantgupta25

### Summary

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2024-08-26 17:58 UTC, nityanandagohain requested changes
Please add test cases to alteast start in that direction, else it will be treated as a secondary citizen and these manual testing will get monotonous.

Checks
- [ ]  static field data type is not shown eg:- severity_text, severity_number 
- [ ] Not able to update the value of operator after running a query ( replaces with old value) ( change the value wait for the suggestion to update then it works but rapid typing doesn't)
- [x] Contains and other filters working properly
- [ ] Filtering from the detail page by clicking on attribute name not working
- [ ] Filter in , filter out from detail page doesn't update the search bar. (refreshing the window makes them appear)
- [ ] There is a flicker after selecting a key value pair.
- [ ] The filter doesn't get cleared if I got to some other page like alerts and come back

Questions ?
* if attr named `x` is of both float and string, then if I type x then is string type selected by default ( that what it seems to be the case)?

Suggestions
* the tag/resource infor feels too far to the right
* the suggestions is scrollable ( the user won't know unless they look extreme right)

2024-08-26 17:58 UTC, nityanandagohain commented on frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
> +					console.log(tagValue, value);
remove

2024-08-27 12:53 UTC, vikrantgupta25 commented on frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
> +					console.log(tagValue, value);
done

2024-08-27 13:18 UTC, vikrantgupta25 commented
@nityanandagohain fixed the 2nd point as discussed, remaining will move to separate issues

2024-08-27 16:08 UTC, nityanandagohain submitted a review, later dismissed
lgtm, please create issue for test and keep it in high priority so that we don't need to go through these tests again for one of the next pr's

2024-08-27 16:12 UTC, vikrantgupta25 commented
@nityanandagohain also addressed the same name different data type issue. if no operator is entered until we show both and do not tokenise and once the operator comes we then pick on priority.

2024-08-28 08:08 UTC, vikrantgupta25 commented
created one P0 task on my name for the test cases - https://github.com/SigNoz/engineering-pod/issues/1724 cc @nityanandagohain

2024-08-29 13:52 UTC, YounixM approved these changes

2024-08-29 14:52 UTC, nityanandagohain approved these changes
LGTM, @srikanthccv do skim through the feature flag part once if somethng looks suspecious/missing, I have less context on it.

2024-08-30 12:20 UTC, merged