fix: added support for `body contains X` tag on pressing enter after selecting attribute key
SigNoz/signoz pull request #6059
Opened 2024-09-24 13:09 UTC by vikrantgupta25

### Summary

- added support for `body contains X` tag on pressing enter after selecting attribute key

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2024-09-24 14:56 UTC, YounixM submitted a review, later dismissed

2024-09-25 06:12 UTC, SagarRajput-7 submitted a review, later dismissed

2024-09-25 07:49 UTC, nityanandagohain requested changes
These quereis not work
* serv abcd def ( matches somethig from the attribute).
* abcd def

2024-09-25 15:00 UTC, YounixM approved these changes

2024-09-25 15:01 UTC, merged