Gitpodify the Signoz
SigNoz/signoz pull request #634
Opened 2022-01-20 19:21 UTC by Siddhant-K-code

As we all know [`signoz/signoz`](https://github.com/SigNoz/signoz) is taking part in GitHub Externship Program. For Me as a beginner, the major block is to set up the project locally.

So, Instead of configuring a local setup, we can use [Gitpod](https://www.gitpod.io/), a VSCode-based Web IDE.

After the merging of this PR, you can directly run this repo. in your browser. It is will be ready to run, build, test & ship 🚀  the new features.

[Detailed Docs about the Gitpod](https://github.com/Siddhant-K-code/signoz/blob/000d1226f9842694ecea8370d8e8d4520ea98e86/CONTRIBUTING.md#L68)

2022-01-27 05:45 UTC, palash-signoz approved these changes

2022-01-27 05:45 UTC, palash-signoz commented on frontend/src/constants/env.ts
> +	baseURL: process?.env?.FRONTEND_API_ENDPOINT || process.env.GITPOD_WORKSPACE_URL.replace('://','://8080-') ||'http://localhost:8080',
can you please add ""

2022-01-27 07:54 UTC, Siddhant-K-code commented on frontend/src/constants/env.ts
> +	baseURL: process?.env?.FRONTEND_API_ENDPOINT || process.env.GITPOD_WORKSPACE_URL.replace('://','://8080-') ||'http://localhost:8080',
Done, Resolved.

2022-01-27 07:54 UTC, ankitnayan requested changes

2022-01-27 07:56 UTC, Siddhant-K-code commented on frontend/webpack.config.js
> +		allowedHosts: 'all',
It is not for production. It is just for the development mode. 


https://github.com/SigNoz/signoz/blob/af9b85f0aa5f2ab72f664306f9753fb78980926c/frontend/webpack.config.js#L30

2022-01-27 07:56 UTC, palash-signoz commented on frontend/webpack.config.js
> +		allowedHosts: 'all',
@Siddhant-K-code can you make this one in dev config ?

2022-01-27 07:58 UTC, Siddhant-K-code commented on frontend/webpack.config.js
> +		allowedHosts: 'all',
> can you make this one in dev config ?

what you wanted to config?

2022-02-08 04:57 UTC, ankitnayan approved these changes

2022-02-08 04:57 UTC, merged

2022-02-08 09:06 UTC, Siddhant-K-code commented
Thanks for Merging It 🚀