feat: added support for instrumentation scope in logs
SigNoz/signoz pull request #6378
Opened 2024-11-06 09:06 UTC by vikrantgupta25

### Summary

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2024-11-06 09:10 UTC, SagarRajput-7 commented on frontend/src/container/LogDetailedView/TableView.tsx
> +
please remove consoles

2024-11-06 09:13 UTC, SagarRajput-7 approved these changes

2024-11-06 09:16 UTC, nityanandagohain requested changes
The group by caluse renders the prefix as well. while the query runs please remove the prefix

![image](https://github.com/user-attachments/assets/f1324204-cfee-495e-a931-73afba3cf207)

2024-11-06 10:37 UTC, vikrantgupta25 commented
> The group by caluse renders the prefix as well. while the query runs please remove the prefix

done @nityanandagohain

2024-11-06 10:46 UTC, nityanandagohain approved these changes

2024-11-06 10:58 UTC, vikrantgupta25 commented on frontend/src/container/QueryBuilder/filters/GroupByFilter/utils.ts
> +	if (str.startsWith(scopePrefix) && type === MetricsType.Scope) {
the change is remove the prefix on the same condition we add the prefix.

2024-11-06 10:59 UTC, vikrantgupta25 commented on frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/OptionRenderer.tsx
> -	const optionType = getOptionType(label);
get the type from the option itself rather than adding to prefix and then removing from prefix and deriving the same. opens up the gates to issues!

2024-11-06 11:00 UTC, vikrantgupta25 commented on frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
> +									!item.isColumn && item.type ? item.type : '',
pass the type on the same condition when the prefix was added so it gets removed only when it's added

2024-11-06 15:26 UTC, SagarRajput-7 approved these changes
lgtm

2024-11-07 05:53 UTC, YounixM approved these changes

2024-11-07 06:02 UTC, rahulkeswani101 approved these changes

2024-11-07 06:16 UTC, srikanthccv approved these changes
I didn't test functionality. Approving to unblock as change in `MetricsApplication` made me reviewer.

2024-11-07 06:17 UTC, merged