build(docker): Two compose files for arm and amd
SigNoz/signoz pull request #638
Opened 2022-01-24 06:13 UTC by prashant-shahi

- remove `--env-file` usage from install script and contributing docs
- use `$HOME/signoz-data` as `data` volume binding for docker
- remove `.gitkeep` files from `data` folder

Signed-off-by: Prashant Shahi <prashant@signoz.io>

2022-01-26 16:13 UTC, prashant-shahi commented
yeah.. will do

2022-01-26 16:58 UTC, pranay01 commented
@prashant-shahi Can you also create a PR on signoz.io repo for updating docs based on this change

2022-01-27 06:11 UTC, prashant-shahi commented
Docs updated: https://github.com/SigNoz/signoz.io/pull/161

2022-01-27 08:00 UTC, ankitnayan requested changes

2022-01-27 12:36 UTC, prashant-shahi commented on deploy/docker/clickhouse-setup/docker-compose.yaml
> +      image: yandex/clickhouse-server:21.12.3.32
I choose `21.12` as I found a matching major-minor version clickhouse image tag for AMD by yandex and ARM by altinity.
Which I wasn't able to find `21.10`.
If we decide to have a matching version then, we could either downgrade to `21.8` or upgrade to `21.12`.
So, I went with the latter.

2022-01-27 16:49 UTC, ankitnayan commented on deploy/docker/clickhouse-setup/docker-compose.yaml
> +      image: yandex/clickhouse-server:21.12.3.32
got it

2022-01-27 17:04 UTC, ankitnayan approved these changes

2022-01-27 17:04 UTC, merged