fix[FE]: fix the update view button not visible on changes to Not Updating in Logs and Traces List View.
SigNoz/signoz pull request #6454
Opened 2024-11-16 08:35 UTC by Aarif5435

## Fix: Update View Button Not Visible and Columns Not Updating in Logs and Traces List View

### Description

This PR resolves two issues related to the "Update View" functionality in the Logs and Traces list view:

1. **Update View Button Not Visible**: After adding or removing columns, the "Update View" button was not appearing. This issue occurred because the comparison logic for detecting changes to the query was flawed—it only compared the old `extraData` (i.e., columns) and failed to account for the newly added or removed columns.
2. **Columns Not Updating After Clicking Update View**: Even after clicking the "Update View" button, the updated columns were not reflected. Upon refreshing the screen, the old columns were still visible because the `updateView` API was being called with outdated `extraData` (i.e., columns), overwriting the new changes with old data.

### Changes Made

- Fixed the issue with the "Update View" button by properly comparing the old `extraData` (columns) with the updated columns to accurately detect changes.
- Updated the `updateView` API call to include the new `extraData` (columns) so that changes persist correctly after clicking the "Update View" button.

### Issue
> The "Update View" button does not appear after making changes to the columns in the Logs and Traces list view. Additionally, even after clicking the button, the updated columns do not persist and revert to the old state upon refreshing the screen.

### Testing
- Verified that the "Update View" button now appears immediately after columns are added or removed.
- Confirmed that after clicking the "Update View" button, the updated columns persist even after refreshing the screen.
- Tested for regressions to ensure existing functionality remains intact.

### Screenshot

https://github.com/user-attachments/assets/51af3e02-4e12-4c91-badd-df25e70816b0

### Notes
This fix ensures a smoother user experience when managing columns in the Logs and Traces list view, allowing users to reliably update and save their preferred view configurations.

2024-11-18 05:43 UTC, YounixM commented
https://67150c0b65fc0b0f718b1a58-hhxvzdwuqv.chromatic.com/?path=/docs/components-pagination--docs - @ahmadshaheer - I am not sure if this is a correct consumption.

2025-01-20 15:12 UTC, ahmadshaheer requested changes
Thanks for making the change @Aarif5435,

Requested a small change.

2025-01-20 15:12 UTC, ahmadshaheer commented on frontend/src/components/ExplorerCard/utils.ts
> +		!isEqual(options?.selectColumns, extraData && JSON.parse(extraData)?.selectColumns)
what will happen if `extraData` is undefined

2025-01-27 12:53 UTC, ahmadshaheer approved these changes

2025-01-29 16:52 UTC, ahmadshaheer approved these changes

2025-02-12 16:58 UTC, YounixM approved these changes

2025-02-13 04:18 UTC, merged