feat: query service waterfall changes for new trace details
SigNoz/signoz pull request #6708
Opened 2024-12-24 12:01 UTC by vikrantgupta25

### Summary

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2024-12-24 12:03 UTC, vikrantgupta25 commented
contributes to - https://github.com/SigNoz/signoz/issues/6132

2025-01-09 08:55 UTC, nityanandagohain requested changes
Have added few comments, the main point will be to add tests for the logics you have implemented.

Apart from that the flux interval should be there and it should be configurable with default set to 1 min.

2025-01-09 08:55 UTC, nityanandagohain commented on pkg/query-service/app/clickhouseReader/reader.go
> +	CacheV2 cacheV2.Cache
can be private instead of public ? `cacheV2`

2025-01-09 08:55 UTC, nityanandagohain commented on pkg/query-service/app/clickhouseReader/reader.go
> +func contains(slice []string, item string) bool {
should go to utils ?

2025-01-09 08:55 UTC, nityanandagohain commented on pkg/query-service/app/clickhouseReader/reader.go
> +		for _, item := range searchScanResponses {
this logic can be moved to utils/traces. And proper test cases

2025-01-14 07:51 UTC, vikrantgupta25 commented on pkg/query-service/app/clickhouseReader/reader.go
> +func contains(slice []string, item string) bool {
done

2025-01-14 07:51 UTC, vikrantgupta25 commented on pkg/query-service/app/clickhouseReader/reader.go
> +	rootToInterestedNodePath = func(node *model.Span) bool {
done

2025-01-14 07:52 UTC, vikrantgupta25 commented on pkg/query-service/app/http_handler.go
> +	router.HandleFunc("/api/v2/traces/{traceId}", am.ViewAccess(aH.SearchTracesV3)).Methods(http.MethodPost)
done

2025-01-14 07:52 UTC, vikrantgupta25 commented on pkg/query-service/model/queryParams.go
> +	InterestedSpanID              string   `json:"interestedSpanId"`
done

2025-01-15 11:37 UTC, nityanandagohain commented on pkg/query-service/app/clickhouseReader/reader.go
> +	rootToInterestedNodePath = func(node *model.Span) bool {
What I suggested was to move it to the common utils package, outside of the clickhouse reader package. Also add tests

2025-01-16 11:27 UTC, vikrantgupta25 commented on pkg/query-service/app/clickhouseReader/reader.go
> +	CacheV2 cacheV2.Cache
done

2025-01-16 11:27 UTC, vikrantgupta25 commented on pkg/query-service/app/clickhouseReader/reader.go
> +			if span.SpanID == req.InterestedSpanID {
done

2025-01-22 19:36 UTC, vikrantgupta25 commented
This PR has been split into 2 PRs - 

https://github.com/SigNoz/signoz/pull/6905  [ frontend ]

https://github.com/SigNoz/signoz/pull/6906. [ query service ]

2025-01-22 19:36 UTC, closed without merging