feat: added new cache package for query service
SigNoz/signoz pull request #6733
Opened 2024-12-30 12:06 UTC by vikrantgupta25

### Summary

#### Related Issues / PR's

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

2025-01-01 18:56 UTC, grandwizard28 requested changes

2025-01-01 18:56 UTC, grandwizard28 commented on pkg/cache/cache.go
> +package cache
There is a new config package that we utilising for this. Let's use that here as well

2025-01-01 18:56 UTC, grandwizard28 commented on pkg/cache/status/status.go
> +package status
This seems like an unnecessary package. We can move this to `pkg/cache/status.go`. It will be semantically better to see `cache.RetrieveStatus` also.

2025-01-01 18:56 UTC, grandwizard28 commented on pkg/cache/entity/entity.go
> +package entity
This seems like an unnecessary package. We can move this to `pkg/cache/cacheable.go`. `cache.Cacheable` seems like a nice reference also.

2025-01-02 08:33 UTC, vikrantgupta25 commented on pkg/cache/status/status.go
> +package status
it will lead to cyclic dependency, the cache pkg imports redis and memory package which needs status package

2025-01-02 08:35 UTC, vikrantgupta25 commented on pkg/cache/entity/entity.go
> +package entity
this will also again lead to cyclic dependency. `memory` and `redis` require the `entity` package which are then imported in the `cache` package

2025-01-03 13:22 UTC, grandwizard28 requested changes

2025-01-03 13:22 UTC, grandwizard28 commented on ee/query-service/main.go
> -		zap.L().Fatal("Failed to create web", zap.Error(err))
@vikrantgupta25 we overrode the skipWebFrontend change here.

We can pass this flag in signoz.New(config, skipWebFrontend) and have an action item on me to incorporate this better for now!

2025-01-03 14:34 UTC, vikrantgupta25 commented on ee/query-service/main.go
> -		zap.L().Fatal("Failed to create web", zap.Error(err))
Added it to the web config itself to keep things centralised in place and to avoid messing up the design pattern

2025-01-03 19:36 UTC, grandwizard28 approved these changes

2025-01-03 19:58 UTC, merged