Fix: update documentation for query-service.
SigNoz/signoz pull request #762
Opened 2022-02-24 10:37 UTC by axaysagathiya

fixes #740

2022-02-24 11:52 UTC, makeavish requested changes

2022-02-24 11:52 UTC, makeavish commented on pkg/query-service/README.md
> +    TORAGE=clickhouse
Typo: STORAGE

2022-02-24 11:52 UTC, makeavish commented on pkg/query-service/README.md
> +ClickHouseUrl=tcp://localhost:9001 TORAGE=clickhouse build/query-service
Typo: STORAGE

2022-02-24 12:04 UTC, makeavish commented on CONTRIBUTING.md
> +- add below configuration to clickhouse section at `docker/clickhouse-setup/docker-compose.yaml`
Preferably please add line number

2022-02-24 12:04 UTC, makeavish approved these changes

2022-02-25 11:35 UTC, ankitnayan approved these changes

2022-02-25 11:35 UTC, merged